bundler_args: --without no_travis
language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.2
env:
  - 'active_support=3.0.0'
  - 'active_support=master'
  - 'curb=0.7.8'
  - 'curb=master'
  - 'yajl-ruby=0.7.7'
  - 'yajl-ruby=master'
  - 'multi_json=0.0.4'
  - 'multi_json=master'
  - 'nokogiri=1.4.3'
  - 'nokogiri=master'
